version: '3'

services:
  microgenerator:
    build:
      context: ./ # Local
      dockerfile: Dockerfile
    #      context: https://github.com/elbosso/generator-microservices.git # Build from Github
    container_name: microgenerator
    hostname: microgenerator
#    ports:
#      - 7000:7000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.generator-microservices.rule=Host(`generator-microservices.docker.lab`)"
      - "traefik.http.services.generator-microservices.loadbalancer.server.port=7000"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy



