version: '3'

services:
  pi-microgenerator:
    build:
      context: ./ # Local
      dockerfile: Dockerfile_arm64
    #      context: https://github.com/elbosso/generator-microservices.git # Build from Github
    container_name: pi-microgenerator
    hostname: pi-microgenerator
#    ports:
#      - 7000:7000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.generator-microservices-http.entrypoints=http"
      - "traefik.http.routers.generator-microservices-http.rule=Host(`generator-microservices.pi-docker.lab`)"
      - "traefik.http.routers.generator-microservices-http.middlewares=generator-microservices-https"
      - "traefik.http.services.generator-microservices-http.loadbalancer.server.port=7000"
      - "traefik.http.middlewares.generator-microservices-https.redirectscheme.scheme=https"
      - "traefik.http.routers.generator-microservices.entrypoints=https"
      - "traefik.http.routers.generator-microservices.rule=Host(`generator-microservices.pi-docker.lab`)"
      - "traefik.http.routers.generator-microservices.tls=true"
      - "traefik.docker.network=pi_traefik_proxy"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: pi_traefik_proxy



