version: '3'

services:
  portainer:
    build: .
    restart: always
#    ports:
#      - 9000:9000
#    volumes:
#      - ./ebooks/epubs:/data
    labels:
      - "traefik.backend=generator-microservices"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:generator-microservices.docker.lab"
      - "traefik.port=7000"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy



